[book]
authors = ["iodapson"]
language = "en"
multilingual = false
src = "src"
title = "Solana Blockchain Guide"

[output.html.playground]
editable = false
copyable = true
line-numbers = false
runnable = false

[build]
build-dir = "docs"
create-missing = false